language: node_js
node_js: 
  - "stable"
before_install: cd api/
install:
      - npm install
script:
      - npm test
cache:
  directories:
    - "api/node_modules"
    - "ui/node_modules"
# whitelist
branches:
  only:
  - travis